version: "3"
services:
  web-app:
    build: .
    container_name: 'nodejs-redis'
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - /home/mag/Nosql/nodejs-redis/api:/api
      #- /home/walter/Descargas/star_wars/api:/api

    depends_on:
      - "db-redis"

  db-redis:
    container_name: 'db-nodejs-redis'
    image: redis
    ports:
      - "6379:6379"
